-- Enable necessary relational extensions
CREATE EXTENSION IF NOT EXISTS ltree;

-- Define user profile partition table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) UNIQUE NOT NULL CHECK (username ~* '^[A-Za-z0-9_]{3,50}$'),
    reputation_score NUMERIC(12, 4) NOT NULL DEFAULT 1.0000 CHECK (reputation_score >= 0.0000),
    invited_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    demographic_group VARCHAR(50) NOT NULL DEFAULT 'urban_affluent' CHECK (demographic_group IN ('urban_affluent', 'remote_rural')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Establish system-wide indexes for profiles
CREATE INDEX IF NOT EXISTS idx_profiles_reputation ON public.profiles(reputation_score DESC);
CREATE INDEX IF NOT EXISTS idx_profiles_invited_by ON public.profiles(invited_by);

-- Define the taxonomic Node table
CREATE TABLE IF NOT EXISTS public.nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES public.nodes(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL CHECK (slug ~* '^[A-Za-z0-9_]{1,255}$'),
    node_type VARCHAR(50) NOT NULL, -- e.g., 'country', 'state', 'city', 'merchant', 'item'
    path ltree NOT NULL UNIQUE,
    address VARCHAR(255),
    coordinates VARCHAR(100),
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chk_node_depth CHECK (nlevel(path) <= 10) -- Prevents infinite loop attacks
);

-- Define decoupled graph tables for taxonomy
CREATE TABLE IF NOT EXISTS public.global_entities (
    entity_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    reference_specification_uri VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.parameterized_archetypes (
    archetype_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    parent_entity_id UUID NOT NULL REFERENCES public.global_entities(entity_id) ON DELETE CASCADE,
    archetype_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.execution_instances (
    instance_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    global_entity_id UUID NOT NULL REFERENCES public.global_entities(entity_id) ON DELETE CASCADE,
    current_archetype_id UUID REFERENCES public.parameterized_archetypes(archetype_id) ON DELETE SET NULL,
    location_name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    coordinates VARCHAR(100),
    gps_dop NUMERIC(4, 2) DEFAULT 1.00,
    deployed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index path structures for rapid subtree lookups
CREATE INDEX IF NOT EXISTS idx_nodes_path_gist ON public.nodes USING GIST(path);
CREATE INDEX IF NOT EXISTS idx_nodes_path_btree ON public.nodes USING BTREE(path);
CREATE INDEX IF NOT EXISTS idx_nodes_parent_id ON public.nodes(parent_id);

-- Define invite token logic
CREATE TABLE IF NOT EXISTS public.invite_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    token_hash VARCHAR(64) UNIQUE NOT NULL, -- SHA-256 representation
    inviter_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    recipient_email VARCHAR(255) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_invites_hash ON public.invite_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_invites_active ON public.invite_tokens(inviter_id) WHERE is_used = FALSE;

-- Define immutable review table
CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    node_id BIGINT NOT NULL REFERENCES public.nodes(id) ON DELETE CASCADE,
    execution_instance_id UUID REFERENCES public.execution_instances(instance_id) ON DELETE SET NULL,
    author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
    raw_content TEXT NOT NULL CHECK (char_length(raw_content) BETWEEN 10 AND 10000),
    is_verified_experience BOOLEAN NOT NULL DEFAULT FALSE,
    param_val_1 NUMERIC(12, 4), -- e.g. Espresso shot weight, GPU Thermal, Outdoor Flow Rate
    param_val_2 NUMERIC(12, 4), -- e.g. Layer division, GPU Clock speed, Outdoor Water Temp
    param_val_3 NUMERIC(12, 4), -- e.g. GPU Voltage
    verification_method VARCHAR(50), -- 'exif_gps', 'wasm_ocr', 'secure_enclave'
    gps_dop NUMERIC(4, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reviews_node_date ON public.reviews(node_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_author ON public.reviews(author_id);

-- Define Vouch / Dispute consensus table
CREATE TABLE IF NOT EXISTS public.vouches_disputes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    review_id UUID NOT NULL REFERENCES public.reviews(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
    type VARCHAR(10) NOT NULL CHECK (type IN ('vouch', 'dispute')),
    allocated_weight NUMERIC(12, 4) NOT NULL, -- Captured from profile reputation score at transaction time
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_user_review_vote UNIQUE (review_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_votes_review ON public.vouches_disputes(review_id, type);

-- Trigger: Automatically build paths on insertion
CREATE OR REPLACE FUNCTION public.trg_populate_node_path()
RETURNS TRIGGER AS $$
DECLARE
    parent_path ltree;
BEGIN
    IF NEW.parent_id IS NULL THEN
        NEW.path := text2ltree(NEW.id::text);
    ELSE
        SELECT path INTO parent_path FROM public.nodes WHERE id = NEW.parent_id;
        IF parent_path IS NULL THEN
            RAISE EXCEPTION 'Parent node with ID % does not exist.', NEW.parent_id;
        END IF;
        NEW.path := parent_path || text2ltree(NEW.id::text);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_nodes_before_insert ON public.nodes;
CREATE TRIGGER trigger_nodes_before_insert
    BEFORE INSERT ON public.nodes
    FOR EACH ROW
    EXECUTE FUNCTION public.trg_populate_node_path();

-- Trigger: Automatically update child paths when moving subtrees
CREATE OR REPLACE FUNCTION public.trg_update_child_paths()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.path IS DISTINCT FROM NEW.path THEN
        UPDATE public.nodes
        SET path = NEW.path || subpath(path, nlevel(OLD.path))
        WHERE path <@ OLD.path AND id <> NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_nodes_after_update ON public.nodes;
CREATE TRIGGER trigger_nodes_after_update
    AFTER UPDATE ON public.nodes
    FOR EACH ROW
    EXECUTE FUNCTION public.trg_update_child_paths();

-- Transactional routine: Dynamic parent node creation
CREATE OR REPLACE FUNCTION public.get_or_create_nested_nodes(
    parent_node_id BIGINT,
    node_payloads JSONB -- Array of JSON objects: [{"name": "Texas", "slug": "texas", "node_type": "state"}]
)
RETURNS BIGINT AS $$
DECLARE
    current_parent_id BIGINT := parent_node_id;
    current_payload JSONB;
    created_id BIGINT;
    existing_id BIGINT;
BEGIN
    -- Lock parent rows to prevent concurrent creation conflicts
    IF current_parent_id IS NOT NULL THEN
        PERFORM id FROM public.nodes WHERE id = current_parent_id FOR SHARE;
    END IF;

    FOR current_payload IN SELECT * FROM jsonb_array_elements(node_payloads) LOOP
        -- Attempt to find an existing node at this level
        SELECT id INTO existing_id 
        FROM public.nodes 
        WHERE (parent_id IS NOT DISTINCT FROM current_parent_id) 
          AND slug = (current_payload->>'slug');

        IF existing_id IS NOT NULL THEN
            current_parent_id := existing_id;
        ELSE
            -- Insert the new node; the BEFORE INSERT trigger populates the path
            INSERT INTO public.nodes (parent_id, name, slug, node_type)
            VALUES (
                current_parent_id, 
                current_payload->>'name', 
                current_payload->>'slug', 
                current_payload->>'node_type'
            )
            RETURNING id INTO created_id;
            
            current_parent_id := created_id;
        END IF;
    END LOOP;

    RETURN current_parent_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Transactional routine: secure invite verification and user creation
CREATE OR REPLACE FUNCTION public.execute_secure_registration(
    p_token_hash VARCHAR(64),
    p_username VARCHAR(50),
    p_password_hash TEXT
)
RETURNS JSONB AS $$
DECLARE
    v_inviter_id UUID;
    v_new_user_id UUID;
    v_profile_data JSONB;
BEGIN
    -- Check token validity and acquire a row-level lock
    SELECT inviter_id INTO v_inviter_id
    FROM public.invite_tokens
    WHERE token_hash = p_token_hash 
      AND is_used = FALSE 
      AND expires_at > now()
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', FALSE, 'message', 'Token invalid, already used, or expired.');
    END IF;

    -- Mark token as used to prevent double-redemption
    UPDATE public.invite_tokens
    SET is_used = TRUE
    WHERE token_hash = p_token_hash;

    -- Generate user profile linked to the inviter
    INSERT INTO public.profiles (username, invited_by, reputation_score)
    VALUES (p_username, v_inviter_id, 1.0000)
    RETURNING id, username, reputation_score INTO v_new_user_id, p_username, v_profile_data;

    RETURN jsonb_build_object(
        'success', TRUE,
        'profile', jsonb_build_object(
            'id', v_new_user_id,
            'username', p_username,
            'reputation_score', 1.0000
        )
    );
EXCEPTION WHEN OTHERS THEN
    -- Any exception triggers an automatic rollback of the transaction
    RETURN jsonb_build_object('success', FALSE, 'message', SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Cascade Revocation Routine
CREATE OR REPLACE FUNCTION public.cascade_revoke_invitation_branch(
    target_malicious_user_id UUID
)
RETURNS TABLE (revoked_user_id UUID, revoked_username VARCHAR(50)) AS $$
BEGIN
    RETURN QUERY
    WITH RECURSIVE invite_blast_radius AS (
        -- Anchor Member: Select the initial compromised profile
        SELECT id, username, invited_by, 1 AS generation
        FROM public.profiles
        WHERE id = target_malicious_user_id
        
        UNION ALL
        
        -- Recursive Member: Traverse downstream accounts
        SELECT p.id, p.username, p.invited_by, ibr.generation + 1
        FROM public.profiles p
        INNER JOIN invite_blast_radius ibr ON p.invited_by = ibr.id
        WHERE ibr.generation < 10 -- Protect against infinite loop attacks
    )
    -- Deactivate accounts and drop their reputations to zero
    UPDATE public.profiles p
    SET is_active = FALSE,
        reputation_score = 0.0000
    FROM invite_blast_radius ibr
    WHERE p.id = ibr.id
    RETURNING p.id, p.username;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Define Tag system tables
CREATE TABLE IF NOT EXISTS public.tags (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL CHECK (name ~* '^[A-Za-z0-9_ -]{2,50}$')
);

CREATE TABLE IF NOT EXISTS public.review_tags (
    review_id UUID NOT NULL REFERENCES public.reviews(id) ON DELETE CASCADE,
    tag_id INT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (review_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_review_tags_tag ON public.review_tags(tag_id);
